stages:
  - lint
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

lint:
  stage: lint
  image: python:3.9
  script:
    - source setup.sh ""
    - ./tests/run_linting
  tags:
    - cvmfs

analysis:
  stage: test
  script:
    - source setup.sh dev
    - bash tests/run_analysis
  tags:
    - cvmfs
  only:
    - merge_requests
    - main
    - triggers
    - web
